alphabot2:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint_lower_camera_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_lower_camera_link
    #pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_upper_camera_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_upper_camera_link
    pid: {p: 100.0, i: 0.01, d: 10.0}
